export const products = [
  {
    id: 1,
    name: "14-inch Irrigation UPVC Pipe",
    material: "UPVC",
    pressureRating: "PN16",
    temperatureRange: "0°C to 60°C",
    length: "6 meters",
    image: "/productimg.svg",
  },
  {
    id: 2,
    name: "10-inch Industrial Drainage Pipe",
    material: "High-Density Polyethylene (HDPE)",
    pressureRating: "PN10",
    temperatureRange: "-10°C to 80°C",
    length: "4 meters",
    image: "/productimg1.svg",
  },
  {
    id: 3,
    name: "8-inch Heavy-Duty Sewer Pipe",
    material: "Reinforced Concrete",
    pressureRating: "PN20",
    temperatureRange: "-5°C to 70°C",
    length: "3 meters",
    image: "/hi-pre4.svg",
  },
  {
    id: 4,
    name: "6-inch PVC Electrical Conduit",
    material: "PVC",
    pressureRating: "PN6",
    temperatureRange: "0°C to 50°C",
    length: "6 meters",
    image: "/hi-pre12.svg",
  },
  {
    id: 5,
    name: "24-inch High-Pressure Water Pipe",
    material: "Galvanized Steel",
    pressureRating: "PN25",
    temperatureRange: "-20°C to 90°C",
    length: "12 meters",
    image: "/hi-pre12.svg",
  },
  {
    id: 6,
    name: "20-inch Underground Sewer Pipe",
    material: "Concrete Fiber",
    pressureRating: "PN18",
    temperatureRange: "-10°C to 60°C",
    length: "8 meters",
    image: "/hi-pre12.svg",
  },
];
